# Generated by Django 3.2.12 on 2022-03-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='Item',
        ),
    ]
