# Generated by Django 3.2.12 on 2022-03-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220326_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Rating',
            new_name='rating',
        ),
    ]
